name = "QSMP \tTRY 2"
author = "Sapo-Lector"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb6651c31f415e0a1829b5ae2af668023d2ee9a12422fa5a76837a3517fe95b1"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
