name = "QSMP \tTRY 2"
author = "Sapo-Lector"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3552ff910eaf2c279bb033b1e53c92ef400ea66d54f9c9e3715a4f74982bb426"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
